select * from customer;

--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer 
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select avg(purchase_amount) as average_spend , shipping_type
from customer
where shipping_type in ('Express','Standard')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,sum(purchase_amount) as total_revenue , avg(purchase_amount) as average_spend ,
count(customer_id) as total_customer
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased, 
    -- We calculate the average of a 1 if discounted, 0 if not. 
    -- This effectively gives us the percentage (ratio).
    AVG(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;

--Q8. What are the top 3 most purchased products within each category?
WITH RankedProducts AS (
    SELECT 
        category, 
        item_purchased, 
        COUNT(*) as purchase_count,
        RANK() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) as pos
    FROM customer
    GROUP BY category, item_purchased
)
SELECT category, item_purchased, purchase_count
FROM RankedProducts
WHERE pos <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, 
count(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
